# Backend Docker Compose
version: "3"	
services: 

  mysql: 	
    image: mysql:latest	
    container_name: DB
    environment:
      - MYSQL_DATABASE=unknownDB
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=1234
    ports:		
      - 3306:3306
    volumes:	
      - ./data/mysql:/var/lib/mysql
    networks:		
      - unknown_network
  
  springboot:
      build:		
        context: dev
        dockerfile: Dockerfile	
      restart: always		
      depends_on:		
        - mysql
      ports:
        - 8080:8080
      container_name: apiServer
      environment:	
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/unknownDB?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: 1234
        SPRING_PROFILES_ACTIVE: dev
      networks:
        - unknown_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    restart: always
    networks:
      - unknown_network

networks:
  unknown_network:
    driver: bridge