# Test Docker Compose
version: '3.8'
services:
 web:
  build:
   context: ./
   target: runner
  container_name: web
  volumes:
   - .:/app
  command: npm run dev
  ports:
   - '3300:3300'
  environment:
   NODE_ENV: development
